WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'confluence.extra.livesearch:livesearch-macro-web-resources', location = 'templates/extra/livesearch/script/livesearch.js' */
AJS.toInit(function(h){var f={userinfo:"icon-user",personalspace:"icon-personal-space"},p=function(a){var b={title:a.title.replace(/&amp;/g,"\x26").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"\x3c").replace(/&gt;/g,"\x3e"),link:[{type:"text/html",rel:"alternate",href:AJS.contextPath()+decodeURI(a.url)}],type:a.contentType};a.searchResultContainer&&(b.space={name:a.searchResultContainer.name});a.metadata&&a.metadata.cssClass&&(b.livesearchIconClass=a.metadata.cssClass);var c=a.contentType;
c&&f[c]&&(b.livesearchIconClass=f[c]);a.bodyTextHighlights&&(b.bodyTextHighlights=a.bodyTextHighlights);return b},k=function(a,b){a.after(a.clone().attr("class","additional").html(b));a.parent().addClass("with-additional")},l=function(a,b,c){return[{title:c,link:[{type:"text/html",rel:"alternate",href:AJS.params.baseUrl+"/dosearchsite.action?queryString\x3d"+a+"\x26where\x3d"+b}],iconClass:"search-for"}]};h(".search-macro-query input").each(function(){var a=h(this),b=a.closest("form"),c=b.find(".aui-icon.aui-iconfont-search"),
g=b.find("input[name\x3d'where']").val(),f=b.find("input[name\x3d'additional']").val(),m=b.find("input[name\x3d'labels']").val(),q=b.find("input[name\x3d'contentType']").val();a.quicksearch("/rest/searchv3/1.0/search",null,{minLengthForGetData:3,dropdownPlacement:function(n){var d=b.siblings(".aui-dd-parent"),c=b.parent(".search-macro").position();d.css({position:"absolute",top:c.top+a.outerHeight(),width:a.outerWidth()});n.width(a.outerWidth());d.append(n)},makeParams:function(a){return{queryString:a,
where:g,labels:m?m.split(","):void 0,type:q,pageSize:5,highlight:!1,sessionUuid:"0-0-0-0"}},makeRestMatrixFromData:function(b){var d=a.val();return b.results&&b.results.length?(b=_.map(b.results,p),[b,l(d,g,AJS.format("See more results for \u0027\u0027{0}\u0027\u0027",d))]):(b=l(d,g,AJS.format("No results found for \u0027\u0027{0}\u0027\u0027",d)))?[b]:[]},dropdownPostprocess:function(a){AJS.$("a",a).each(function(){var a=h(this),b=a.find("span"),c=a.parent("li"),e=AJS.dropDown.getAdditionalPropertyValue(b,
"restObj");if(e&&e.livesearchIconClass){var g=AJS.dropDown.getAdditionalPropertyValue(b,"iconClass");a.removeClass(g);b.addClass(e.livesearchIconClass)}"space name"===f?(b=AJS.dropDown.getAdditionalPropertyValue(b,"spaceName"))&&!a.is(".content-type-spacedesc")&&k(a,b):"page excerpt"===f&&e.bodyTextHighlights&&k(a,e.bodyTextHighlights);c.attr("data-content-type",e.type)})},ajsDropDownOptions:{className:"search-macro-dropdown"}});a.on({"quick-search-loading-start":function(){c.addClass("aui-icon-wait").removeClass("aui-iconfont-search")},
"quick-search-loading-stop":function(){c.removeClass("aui-icon-wait").addClass("aui-iconfont-search")}})})});
}catch(e){WRMCB(e)};